version: '3.8'
networks:
  application:
    driver: bridge
services:
#  keycloak_postgres:
  postgres:
    container_name: keycloak_postgres
    image: postgres:${POSTGRES_VERSION:-latest}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data # all changes in database will be stored in this volume
      - ./postgres_init/01-init.sh:/docker-entrypoint-initdb.d/init-db.sh # used only first time container is built to create database and users
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "KEYCLOAK_DB=keycloak"
      - "KEYCLOAK_DB_USER=keycloak"
      - "KEYCLOAK_DB_PASSWORD=keycloak"
      - "KEYCLOAK_DB_SCHEMA=keycloak"
    ports:
      - "5442:5432"
    expose:
      - 5442
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "postgres", "-U", "postgres" ]
      timeout: 5s
      interval: 10s
      retries: 10
    restart: "no"
    networks:
      - ${GLOBAL_NETWORK:-postgres}
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
  keycloak-authorization-server:
    container_name: keycloak-server
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-latest}
    hostname: keycloak-server
    ports:
      - "9091:9091"
    volumes:
      - ./keycloak/realms/export:/tmp/export
#      - ./check-postgres-started.sh:/opt/keycloak/bin/check-postgres-started.sh
#    entrypoint: [ "sh", "-c", "/opt/keycloak/bin/check-postgres-started.sh && /opt/keycloak/bin/kc.sh", "start-dev", "--http-port", "9091" ]
#    entrypoint: [ "sh", "-c", "/opt/keycloak/bin/check-postgres-started.sh" ]
    entrypoint: [ "/opt/keycloak/bin/kc.sh", "start-dev", "--http-port", "9091" ]
#    command: ./check-postgres-started.sh
    environment:
      - "KEYCLOAK_ADMIN=admin"
      - "KEYCLOAK_ADMIN_PASSWORD=admin"
      - "KC_LOG_LEVEL=INFO"
      - "KC_DB=postgres" # database type
      - "KC_DB_USERNAME=keycloak"
      - "KC_DB_PASSWORD=keycloak"
      - "KC_DB_SCHEMA=keycloak" # only public schema works?
      - "KC_DB_URL_DATABASE=keycloak" # database to use
      - "KC_DB_URL_HOST=postgres" # postgres service defined above
      - "KC_DB_URL_PORT=5432"
    # https://docs.docker.com/compose/compose-file/05-services/#depends_on
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ${GLOBAL_NETWORK:-postgres}
volumes:
  postgres_data:
    driver: local