version: '3.8'
services:
  grafana:
    container_name: grafana
    image: grafana/grafana:${GRAFANA_VERSION:-latest}
    hostname: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana:/var/lib/grafana
#      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - ${GLOBAL_NETWORK:-grafana}
  prometheus:
    container_name: prometheus
    image: prom/prometheus:${PROMETHEUS_VERSION:-latest}
    hostname: prometheus
    ports:
      - 9090:9090
    expose:
      - 9090
    volumes:
      - ./config/prometheus_local.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    networks:
      - ${GLOBAL_NETWORK:-prometheus}
